// generated by stringer -type=APNSErrorCode; DO NOT EDIT

package main

import "fmt"

const _APNSErrorCode_name = "ErrAPNSNoErrorsErrAPNSProcessingErrAPNSMissingDeviceTokenErrAPNSMissingTopicErrAPNSMissingPayloadErrAPNSInvalidTokenSizeErrAPNSInvalidTopicSizeErrAPNSInvalidPayloadSizeErrAPNSInvalidTokenErrAPNSShutdown"

var _APNSErrorCode_index = [...]uint8{0, 15, 32, 57, 76, 97, 120, 143, 168, 187, 202}

func (i APNSErrorCode) String() string {
	if i < 0 || i >= APNSErrorCode(len(_APNSErrorCode_index)-1) {
		return fmt.Sprintf("APNSErrorCode(%d)", i)
	}
	return _APNSErrorCode_name[_APNSErrorCode_index[i]:_APNSErrorCode_index[i+1]]
}
